add_item:
  name: Add item
  description: Add an item to the shopping list.
  fields:
    name:
      name: Name
      description: The name of the item to add.
      required: true
      example: Beer
      selector:
        text:

complete_item:
  name: Complete item
  description: Mark an item as completed in the shopping list.
  fields:
    name:
      name: Name
      description: The name of the item to mark as completed (without removing).
      required: true
      example: Beer
      selector:
        text:
